# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=2.0.0+1.21.1
group=xyz.hajsori
java_version=21
# Common
minecraft_version=1.21.1
min_minecraft_version=1.21
excluded_minecraft_version=1.21.2
mod_name=QuickList
mod_author=Hajsori
mod_id=quicklist
license=MIT
credits=Both features (quick search and to-do list) are inspired by Satisfactory; Thanks to Emi for making the EMI Mod; This Mod uses the exp4j Library, which is licensed under the Apache License 2.0
description=With QuickList you can search for any item in the Game by pressing [N] (by default), you can calculate things AND you have a nice To-Do List! (Inspired by Satisfactory)
neo_form_version=1.21-20240613.152323
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.06.23
# Fabric
fabric_version=0.116.12+1.21.1
fabric_loader_version=0.19.2
# Forge
forge_version=51.0.17
forge_loader_version_range=[51,)
# NeoForge
neoforge_version=21.0.37-beta
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# EMI
emi_version=1.1.12+1.21
# exp4j
exp4j_version=0.4.8
